### ISSUE TITLE
[BOTW] Stables and Sellers inventory blur causing massive FPS drops

### ISSUE THREAD

**Issue by valentyn-l** [cemu-project/cemu_graphic_packs#530]
Hello!

I'd like to report a bug where the FPS drops massively when interacting with the Stables master or Shop vendors like Beedle. The problem occurs as soon as the selection menu appears, which coincidentally is also when the background gets blurred. This leads me to believe that the FPS drop is due to the upscaling of this effect.

I have tested this without the Graphics pack, running at the native 1280x720 resolution and the problem is gone.

I've attached screenshots of the game running as normal, and the menu with the FPS drop.

You can see details of system resource usage and FPS in the top left corner.

![1](https://user-images.githubusercontent.com/60371520/130331573-35d57b40-8090-4dc0-b383-129dca9ca7bf.png)
![2](https://user-images.githubusercontent.com/60371520/130331577-23809338-5a9e-4f3b-8b64-08a63aa99ccd.png)

**Comment by skalfate** [comment]
Hi,

I do know that there is some fps loss for a second or so when opening them for the first time at each gaming session but it should not be so severely as it is in your case going from 61 to 22 FPS.

I tried this on cemu 1.25.1 on v4 packs and the latest v6 packs and I only got about [4-6] fps loss in 21/9 aspect ratio, 1440p resolution, and opengl mode opening the stable menu and shop menu.

Can you possibly share your log file after you load into game and then exit while using opengl instead of vulkan please.

**Comment by Squall-Leonhart** [comment]
This is fixed in https://github.com/cemu-project/Cemu/issues/380

Can be closed
